name: CI

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          ruby \
          qmake6 \
          libqt6core6 \
          libqt6gui6 \
          libqt6svg6-dev \
          libqt6core5compat6-dev \
          zlib1g-dev \
          libgl1-mesa-dev \
          libssl-dev \
          qt6-base-dev \
          qt6-svg-dev
          
    - name: Prepare environment
      run: ruby prepare.rb
      
    - name: Build libfiletype
      run: |
        rm -fr _build_libfiletype
        mkdir _build_libfiletype
        cd _build_libfiletype
        qmake6 "CONFIG+=release" ../filetype/libfiletype.pro
        make -j$(nproc)
        
    - name: Build Guitar
      run: |
        rm -fr _build_guitar
        mkdir _build_guitar
        cd _build_guitar
        qmake6 "CONFIG+=release" ../Guitar.pro
        make -j$(nproc)
        
    - name: Test build
      run: |
        ls -la _bin/
        file _bin/Guitar
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: guitar-linux-amd64
        path: _bin/Guitar

  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Qt6
      run: |
        brew install qt@6 ruby
        echo "/opt/homebrew/opt/qt@6/bin" >> $GITHUB_PATH
        
    - name: Prepare environment
      run: ruby prepare.rb
      
    - name: Build libfiletype
      run: |
        rm -fr _build_libfiletype
        mkdir _build_libfiletype
        cd _build_libfiletype
        qmake "CONFIG+=release" ../filetype/libfiletype.pro
        make -j$(sysctl -n hw.ncpu)
        
    - name: Build Guitar
      run: |
        rm -fr _build_guitar
        mkdir _build_guitar
        cd _build_guitar
        qmake "CONFIG+=release" ../Guitar.pro
        make -j$(sysctl -n hw.ncpu)
        
    - name: Test build
      run: |
        ls -la _bin/
        file _bin/Guitar
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: guitar-macos
        path: _bin/Guitar

  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Qt6
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.7.0'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        
    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v2
      
    - name: Setup Visual Studio environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        
    - name: Verify environment
      run: |
        Write-Host "Checking environment variables..."
        Write-Host "VCINSTALLDIR: $env:VCINSTALLDIR"
        Write-Host "PATH includes nmake: $((Get-Command nmake -ErrorAction SilentlyContinue) -ne $null)"
        Write-Host "PATH includes qmake: $((Get-Command qmake -ErrorAction SilentlyContinue) -ne $null)"
      shell: pwsh
      
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        
    - name: Prepare environment
      run: ruby prepare.rb
      shell: bash
      
    - name: Build libfiletype
      run: |
        if (Test-Path "_build_libfiletype") { Remove-Item -Recurse -Force "_build_libfiletype" }
        New-Item -ItemType Directory -Path "_build_libfiletype"
        Set-Location "_build_libfiletype"
        qmake "CONFIG+=release" ../filetype/libfiletype.pro
        nmake
        Set-Location ".."
      shell: pwsh
      
    - name: Build Guitar
      run: |
        if (Test-Path "_build_guitar") { Remove-Item -Recurse -Force "_build_guitar" }
        New-Item -ItemType Directory -Path "_build_guitar"
        Set-Location "_build_guitar"
        qmake "CONFIG+=release" ../Guitar.pro
        nmake
        Set-Location ".."
      shell: pwsh
      
    - name: Test build
      run: |
        Get-ChildItem "_bin/"
        if (Test-Path "_bin/Guitar.exe") {
          Write-Host "Guitar.exe found"
        } else {
          Write-Host "Guitar.exe not found"
          exit 1
        }
      shell: pwsh
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: guitar-windows-x64
        path: _bin/Guitar.exe
