name: CI

on:
  workflow_dispatch:

jobs:
  build-linux:
    if: false  # Temporarily disabled
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          ruby \
          qmake6 \
          libqt6core6 \
          libqt6gui6 \
          libqt6svg6-dev \
          libqt6core5compat6-dev \
          zlib1g-dev \
          libgl1-mesa-dev \
          libssl-dev \
          qt6-base-dev \
          qt6-svg-dev
          
    - name: Prepare environment
      run: ruby prepare.rb
      
    - name: Build libfiletype
      run: |
        rm -fr _build_libfiletype
        mkdir _build_libfiletype
        cd _build_libfiletype
        qmake6 "CONFIG+=release" ../filetype/libfiletype.pro
        make -j$(nproc)
        
    - name: Build Guitar
      run: |
        rm -fr _build_guitar
        mkdir _build_guitar
        cd _build_guitar
        qmake6 "CONFIG+=release" ../Guitar.pro
        make -j$(nproc)
        
    - name: Test build
      run: |
        ls -la _bin/
        file _bin/Guitar
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: guitar-linux-amd64
        path: _bin/Guitar

  build-macos:
    if: false  # Temporarily disabled
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Qt6
      run: |
        brew install qt@6 ruby
        echo "/opt/homebrew/opt/qt@6/bin" >> $GITHUB_PATH
        
    - name: Prepare environment
      run: ruby prepare.rb
      
    - name: Build libfiletype
      run: |
        rm -fr _build_libfiletype
        mkdir _build_libfiletype
        cd _build_libfiletype
        qmake "CONFIG+=release" ../filetype/libfiletype.pro
        make -j$(sysctl -n hw.ncpu)
        
    - name: Build Guitar
      run: |
        rm -fr _build_guitar
        mkdir _build_guitar
        cd _build_guitar
        qmake "CONFIG+=release" ../Guitar.pro
        make -j$(sysctl -n hw.ncpu)
        
    - name: Test build
      run: |
        ls -la _bin/
        file _bin/Guitar
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: guitar-macos
        path: _bin/Guitar

  build-windows-mingw:
    if: false  # Temporarily disabled
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Qt6
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.7.0'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw'
        
    - name: Setup MinGW
      run: |
        choco install mingw -y
        refreshenv
      shell: cmd
      
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        
    - name: Prepare environment
      run: ruby prepare.rb
      shell: bash
      
    - name: Build libfiletype
      run: |
        if exist "_build_libfiletype" rmdir /s /q "_build_libfiletype"
        mkdir "_build_libfiletype"
        cd "_build_libfiletype"
        qmake "CONFIG+=release" ../filetype/libfiletype.pro
        mingw32-make
        cd ..
      shell: cmd
      
    - name: Build Guitar
      run: |
        if exist "_build_guitar" rmdir /s /q "_build_guitar"
        mkdir "_build_guitar"
        cd "_build_guitar"
        qmake "CONFIG+=release" ../Guitar.pro
        mingw32-make
        cd ..
      shell: cmd
      
    - name: Test build
      run: |
        dir "_bin\"
        if exist "_bin\Guitar.exe" (
          echo Guitar.exe found
        ) else (
          echo Guitar.exe not found
          exit /b 1
        )
      shell: cmd
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: guitar-windows-mingw-x64
        path: _bin/Guitar.exe

  build-windows-msvc2022:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Qt6
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.3'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2022_64'
        
    - name: Setup MSVC 2022
      uses: microsoft/setup-msbuild@v2
      
    - name: Setup Visual Studio 2022 environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        vsversion: 2022
        
    - name: Verify environment
      run: |
        echo Checking environment variables...
        echo VCINSTALLDIR: %VCINSTALLDIR%
        echo VisualStudioVersion: %VisualStudioVersion%
        echo QMAKESPEC: %QMAKESPEC%
        where nmake
        where qmake
        qmake -query QT_VERSION
        qmake -query QMAKE_SPEC
      shell: cmd
        
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        
    - name: Prepare environment
      run: ruby prepare.rb
      shell: bash
      
    - name: Build zlib
      run: |
        git clone https://github.com/madler/zlib.git
        if exist "_build_zlib" rmdir /s /q "_build_zlib"
        mkdir "_build_zlib"
        cd "_build_zlib"
        qmake -spec win32-msvc "CONFIG+=release" ../zlib.pro
        dir
        nmake /f Makefile.Release
        cd ..
      shell: cmd
      
    - name: Build libfiletype
      run: |
        if exist "_build_libfiletype" rmdir /s /q "_build_libfiletype"
        mkdir "_build_libfiletype"
        cd "_build_libfiletype"
        qmake -spec win32-msvc "CONFIG+=release" ../filetype/libfiletype.pro
        nmake /f Makefile.Release
        cd ..
      shell: cmd
      
    - name: Build Guitar
      run: |
        if exist "_build_guitar" rmdir /s /q "_build_guitar"
        mkdir "_build_guitar"
        cd "_build_guitar"
        qmake -spec win32-msvc "CONFIG+=release" ../Guitar.pro
        nmake /f Makefile.Release
        cd ..
      shell: cmd
      
    - name: Test build
      run: |
        dir "_bin\"
        if exist "_bin\Guitar.exe" (
          echo Guitar.exe found
        ) else (
          echo Guitar.exe not found
          exit /b 1
        )
      shell: cmd
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: guitar-windows-msvc2022-x64
        path: _bin/Guitar.exe
